[build]
 command= "CI= npm run build"
 commandOrigin = "ui"
[[redirects]]
  from = "/login"
  to = "https://charlotteetflorian.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
